# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS app

ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable

WORKDIR /workspace

COPY . .

ARG APP_FILTER
ENV APP_FILTER=${APP_FILTER}

ARG NEXT_PUBLIC_PLATFORM_SHELL_NAME=
ARG NEXT_PUBLIC_MICRO_APP_VITE_REFRESH=
ARG NEXT_PUBLIC_CUSTOMER_APP_ORIGIN=
ARG NEXT_PUBLIC_BILLING_APP_ORIGIN=
ARG NEXT_PUBLIC_ANALYTICS_APP_ORIGIN=
ARG NEXT_PUBLIC_ADMIN_APP_ORIGIN=
ARG NEXT_PUBLIC_AI_ASSISTANT_APP_ORIGIN=
ARG NEXT_PUBLIC_VUE_COMMERCE_APP_ORIGIN=
ARG NEXT_PUBLIC_ANGULAR_OPS_APP_ORIGIN=
ARG NEXT_PUBLIC_DESIGN_SYSTEM_APP_ORIGIN=
ARG NEXT_PUBLIC_MCP_DEMO_APP_ORIGIN=
ARG NEXT_PUBLIC_CUSTOMER_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_BILLING_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_ANALYTICS_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_ADMIN_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_AI_ASSISTANT_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_VUE_COMMERCE_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_ANGULAR_OPS_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_DESIGN_SYSTEM_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_MCP_DEMO_APP_ENTRY_PATH=
ARG NEXT_PUBLIC_CUSTOMER_APP_STYLE_PATH=
ARG NEXT_PUBLIC_BILLING_APP_STYLE_PATH=
ARG NEXT_PUBLIC_ANALYTICS_APP_STYLE_PATH=
ARG NEXT_PUBLIC_ADMIN_APP_STYLE_PATH=
ARG NEXT_PUBLIC_AI_ASSISTANT_APP_STYLE_PATH=
ARG NEXT_PUBLIC_VUE_COMMERCE_APP_STYLE_PATH=
ARG NEXT_PUBLIC_ANGULAR_OPS_APP_STYLE_PATH=
ARG NEXT_PUBLIC_DESIGN_SYSTEM_APP_STYLE_PATH=
ARG NEXT_PUBLIC_MCP_DEMO_APP_STYLE_PATH=

ENV NEXT_PUBLIC_PLATFORM_SHELL_NAME=${NEXT_PUBLIC_PLATFORM_SHELL_NAME}
ENV NEXT_PUBLIC_MICRO_APP_VITE_REFRESH=${NEXT_PUBLIC_MICRO_APP_VITE_REFRESH}
ENV NEXT_PUBLIC_CUSTOMER_APP_ORIGIN=${NEXT_PUBLIC_CUSTOMER_APP_ORIGIN}
ENV NEXT_PUBLIC_BILLING_APP_ORIGIN=${NEXT_PUBLIC_BILLING_APP_ORIGIN}
ENV NEXT_PUBLIC_ANALYTICS_APP_ORIGIN=${NEXT_PUBLIC_ANALYTICS_APP_ORIGIN}
ENV NEXT_PUBLIC_ADMIN_APP_ORIGIN=${NEXT_PUBLIC_ADMIN_APP_ORIGIN}
ENV NEXT_PUBLIC_AI_ASSISTANT_APP_ORIGIN=${NEXT_PUBLIC_AI_ASSISTANT_APP_ORIGIN}
ENV NEXT_PUBLIC_VUE_COMMERCE_APP_ORIGIN=${NEXT_PUBLIC_VUE_COMMERCE_APP_ORIGIN}
ENV NEXT_PUBLIC_ANGULAR_OPS_APP_ORIGIN=${NEXT_PUBLIC_ANGULAR_OPS_APP_ORIGIN}
ENV NEXT_PUBLIC_DESIGN_SYSTEM_APP_ORIGIN=${NEXT_PUBLIC_DESIGN_SYSTEM_APP_ORIGIN}
ENV NEXT_PUBLIC_MCP_DEMO_APP_ORIGIN=${NEXT_PUBLIC_MCP_DEMO_APP_ORIGIN}
ENV NEXT_PUBLIC_CUSTOMER_APP_ENTRY_PATH=${NEXT_PUBLIC_CUSTOMER_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_BILLING_APP_ENTRY_PATH=${NEXT_PUBLIC_BILLING_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_ANALYTICS_APP_ENTRY_PATH=${NEXT_PUBLIC_ANALYTICS_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_ADMIN_APP_ENTRY_PATH=${NEXT_PUBLIC_ADMIN_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_AI_ASSISTANT_APP_ENTRY_PATH=${NEXT_PUBLIC_AI_ASSISTANT_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_VUE_COMMERCE_APP_ENTRY_PATH=${NEXT_PUBLIC_VUE_COMMERCE_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_ANGULAR_OPS_APP_ENTRY_PATH=${NEXT_PUBLIC_ANGULAR_OPS_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_DESIGN_SYSTEM_APP_ENTRY_PATH=${NEXT_PUBLIC_DESIGN_SYSTEM_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_MCP_DEMO_APP_ENTRY_PATH=${NEXT_PUBLIC_MCP_DEMO_APP_ENTRY_PATH}
ENV NEXT_PUBLIC_CUSTOMER_APP_STYLE_PATH=${NEXT_PUBLIC_CUSTOMER_APP_STYLE_PATH}
ENV NEXT_PUBLIC_BILLING_APP_STYLE_PATH=${NEXT_PUBLIC_BILLING_APP_STYLE_PATH}
ENV NEXT_PUBLIC_ANALYTICS_APP_STYLE_PATH=${NEXT_PUBLIC_ANALYTICS_APP_STYLE_PATH}
ENV NEXT_PUBLIC_ADMIN_APP_STYLE_PATH=${NEXT_PUBLIC_ADMIN_APP_STYLE_PATH}
ENV NEXT_PUBLIC_AI_ASSISTANT_APP_STYLE_PATH=${NEXT_PUBLIC_AI_ASSISTANT_APP_STYLE_PATH}
ENV NEXT_PUBLIC_VUE_COMMERCE_APP_STYLE_PATH=${NEXT_PUBLIC_VUE_COMMERCE_APP_STYLE_PATH}
ENV NEXT_PUBLIC_ANGULAR_OPS_APP_STYLE_PATH=${NEXT_PUBLIC_ANGULAR_OPS_APP_STYLE_PATH}
ENV NEXT_PUBLIC_DESIGN_SYSTEM_APP_STYLE_PATH=${NEXT_PUBLIC_DESIGN_SYSTEM_APP_STYLE_PATH}
ENV NEXT_PUBLIC_MCP_DEMO_APP_STYLE_PATH=${NEXT_PUBLIC_MCP_DEMO_APP_STYLE_PATH}

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @micro-frontend/design-system build
RUN pnpm --filter @openmf/core build
RUN pnpm --filter "${APP_FILTER}" build

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV APP_KIND=remote

CMD if [ "$APP_KIND" = "shell" ]; then \
      pnpm --filter "$APP_FILTER" start -H 0.0.0.0 -p "$PORT"; \
    elif [ "$APP_KIND" = "mcp" ]; then \
      pnpm --filter "$APP_FILTER" start; \
    else \
      pnpm --filter "$APP_FILTER" preview --host 0.0.0.0 --port "$PORT"; \
    fi
